# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gate.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngate.proto\x12\x04gate\"/\n\x0cMasukRequest\x12\x0f\n\x07idkartu\x18\x01 \x01(\x05\x12\x0e\n\x06idgate\x18\x02 \x01(\x05\"\x1f\n\rMasukResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\"0\n\rKeluarRequest\x12\x0f\n\x07idkartu\x18\x01 \x01(\x05\x12\x0e\n\x06idgate\x18\x02 \x01(\x05\" \n\x0eKeluarResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32x\n\x0bGateService\x12\x32\n\x05masuk\x12\x12.gate.MasukRequest\x1a\x13.gate.MasukResponse\"\x00\x12\x35\n\x06keluar\x12\x13.gate.KeluarRequest\x1a\x14.gate.KeluarResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'gate_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MASUKREQUEST._serialized_start=20
  _MASUKREQUEST._serialized_end=67
  _MASUKRESPONSE._serialized_start=69
  _MASUKRESPONSE._serialized_end=100
  _KELUARREQUEST._serialized_start=102
  _KELUARREQUEST._serialized_end=150
  _KELUARRESPONSE._serialized_start=152
  _KELUARRESPONSE._serialized_end=184
  _GATESERVICE._serialized_start=186
  _GATESERVICE._serialized_end=306
# @@protoc_insertion_point(module_scope)
