# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import gate_pb2 as gate__pb2


class GateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.masuk = channel.unary_unary(
                '/gate.GateService/masuk',
                request_serializer=gate__pb2.MasukRequest.SerializeToString,
                response_deserializer=gate__pb2.MasukResponse.FromString,
                )
        self.keluar = channel.unary_unary(
                '/gate.GateService/keluar',
                request_serializer=gate__pb2.KeluarRequest.SerializeToString,
                response_deserializer=gate__pb2.KeluarResponse.FromString,
                )


class GateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def masuk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def keluar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'masuk': grpc.unary_unary_rpc_method_handler(
                    servicer.masuk,
                    request_deserializer=gate__pb2.MasukRequest.FromString,
                    response_serializer=gate__pb2.MasukResponse.SerializeToString,
            ),
            'keluar': grpc.unary_unary_rpc_method_handler(
                    servicer.keluar,
                    request_deserializer=gate__pb2.KeluarRequest.FromString,
                    response_serializer=gate__pb2.KeluarResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gate.GateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def masuk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gate.GateService/masuk',
            gate__pb2.MasukRequest.SerializeToString,
            gate__pb2.MasukResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def keluar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/gate.GateService/keluar',
            gate__pb2.KeluarRequest.SerializeToString,
            gate__pb2.KeluarResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
